vim.g.mapleader = ","

vim.cmd("set expandtab")
vim.cmd("set tabstop=2")
vim.cmd("set softtabstop=2")
vim.cmd("set shiftwidth=2")
vim.cmd("set number")
-- vim.cmd("set relativenumber")
vim.cmd("set encoding=utf-8")
vim.cmd("set fileencoding=utf-8")
vim.cmd("set fileencodings=utf-8")
vim.cmd("set tabstop=2")
vim.cmd("set softtabstop=0")
vim.cmd("set shiftwidth=2")
vim.cmd("set expandtab")
vim.cmd("set incsearch")
vim.cmd("set ignorecase")
vim.cmd("set smartcase")
vim.cmd("set nobackup")
vim.cmd("set noswapfile")
vim.cmd("set wildignore+=*.map,*.gz,.git,node_modules")
vim.cmd("set splitbelow")
vim.cmd("set splitright")
vim.cmd("set history=1000")
vim.cmd("set undofile")
vim.cmd("set undolevels=1000")
vim.cmd("set undodir=~/.vim/.undo")
vim.cmd("set spelllang=ru,en")
vim.cmd("set list")
vim.cmd("set listchars=tab:>-,trail:~,extends:>,precedes:<")
vim.cmd("set fixendofline")
vim.cmd("set ruler")
vim.cmd("set colorcolumn=100")
vim.cmd("set t_Co=256")
